### ISSUE TITLE
Aspnet Core project not working on VS 2017 RC

### ISSUE THREAD

**Issue by sohaibjaved44** [aspnetboilerplate/aspnet-core-template#13] opened 2017-01-02 15:04 UTC
Hi, 
     Hope you are doing well, I have downloaded aspnet Core project and I'm running it on VS2017, I am unable to restore packages facing errors, I then explored web where I found that Project.json file is deprecated in vs2017 which comes with preview4 by default, in preview3+ project.json donot works, projects gets restored using MSBuild. 
Please let me know do we have a solution to run in VS2017? can you fix this solution to work on VS2017 RC?
Looking forward to hear from you.
Thanks,
Sohaib

**Comment by hikalkan** [comment] 2017-01-03 11:25
Hi,

VS 2017 may not properly work with project.json format. But Microsoft promised to automatically migrate project.json based solutions. Maybe tooling is not completed yet.
So, we don't have a solution for it yet and waiting Microsoft to finalize it's tooling to auto-migrate the solution.
Actually I don't suggest to use VS 2017 in production yet since it's very buggy as I heard, especially for tooling.

**Comment by sohaibjaved44** [comment] 2017-01-03 13:11
OK thanks for suggestion, one more thing how about preview4 it comes with vs2017 as I have installed VS2017, and how about preview2 can we use it with this solution? or I need to install preview4 with VS2015?
Thank you so much.
Sohaib

**Comment by sohaibjaved44** [comment] 2017-01-05 05:51
Hi Halil, 
     I'm looking forward to hear from you. Your response would be a great help.
thanks
Sohaib

**Comment by sohaibjaved44** [comment] 2017-01-05 18:52
This error occurs on startup when I run it in VS 2015


![image](https://cloud.githubusercontent.com/assets/8418548/21693236/f8d552b8-d3a1-11e6-9abb-1ee842a391f1.png)

**Comment by hikalkan** [comment] 2017-01-06 12:03
Hi,

If you first opened solution with VS 2017, maybe it changed the SDK version from global.json
Normally, we don't add SDK version to this file to allow VS to use the latest.
In my PC, preview2-1-003177 is installed, but I think VS 2015 will also work with preview2-003131.

**Comment by heavenwing** [comment] 2017-03-11 07:12
Also not working in VS 2017 RTM

**Comment by hikalkan** [comment] 2017-03-11 11:55
When you open it in VS 2017, VS automatically converts the project format. But in some cases, additional manual work may be needed. We converted a larget solution (and ABP framework) to VS2017.
We will convert this solution too.

**Comment by ismcagdas** [comment] 2017-03-28 05:37
Duplicate of https://github.com/aspnetboilerplate/aspnet-core-template/issues/21

**Closed by ismcagdas** 2017-03-28 05:37 UTC
