### ISSUE TITLE
Free Startup Templates page - "One solution" checkbox

### ISSUE THREAD

**Issue by dedlfix** [aspnetboilerplate/aspnet-core-template#57] opened 2018-02-23 08:14 UTC
I don't know if this is the right place for this issue, but ...

Open the [Startup Templates page](https://aspnetboilerplate.com/Templates). switch from ASP.NET Core 2x to ASP.NET MVC 5.x. Uncheck "Include login, register, user, role and tenant management pages.". Go back to ASP.NET Core 2x. Now the (recently added) "One solution" checkbox including the text is gone and never comes back until you reload the page.

While you're at it, you should markup the text as `<label for="id of the checkbox">` so that you can also click the text to switch the checkbox not only the little checkbox itself. (It is also better for assistive techniques like screen readers to indcate that the text belongs to the checkbox, i.e. is its label.)

**Comment by hikalkan** [comment] 2018-02-23 08:33
Thanks for the bug report. Will fix this.

**Comment by alirizaadiyahsi** [comment] 2018-02-26 08:47
I can't reproduce your issue. There are 3 condition to show "One solution ..." checkbox.

- Active tab should be "ASP.NET Core 2.x"
- "Angular" should be checked
- "Include login" should be checked

I think you missed "Angular" should be checked. Because when you go back from "Mvc 5x" tab with unchecked "Include login", then "Multi-Page Web Application" is seleted.

**Comment by dedlfix** [comment] 2018-02-26 14:16
It is either fixed already or I indeed did not clicked on Angular again. However, the `<label>` still should be set for the checkboxes.

**Comment by alirizaadiyahsi** [comment] 2018-02-26 14:25
> However, the <label> still should be set for the checkboxes.

This will be fixed next aspnetboilerplate.com release.

**Closed by alirizaadiyahsi** 2018-02-26 14:25 UTC
Labels: bug
