### ISSUE TITLE
dotnet ef database update throwing No executable found matching command "dotnet-ef"

### ISSUE THREAD

**Issue by jotamorais** [aspnetboilerplate/aspnet-core-template#4] opened 2016-07-06 19:45 UTC
Hi there,

I've followed instruction from [How to run section](https://github.com/aspnetboilerplate/aspnet-core-template#how-to-run) and it's throwing `No executable found matching command "dotnet-ef"`

After cloning the repo, I ran:

`PM> dotnet restore`

and got:

```
log  : Restoring packages for C:\Development\Researchs\DotNetCore\MyCoreApp\src\AbpCompanyName.AbpProjectName.EntityFrameworkCore\project.json...
info : Committing restore...
log  : Lock file has not changed. Skipping lock file write. Path: C:\Development\Researchs\DotNetCore\MyCoreApp\src\AbpCompanyName.AbpProjectName.EntityFrameworkCore\project.lock.json
log  : C:\Development\Researchs\DotNetCore\MyCoreApp\src\AbpCompanyName.AbpProjectName.EntityFrameworkCore\project.json
log  : Restore completed in 509ms.

NuGet Config files used:
    C:\Users\jonathas_morais\AppData\Roaming\NuGet\NuGet.Config
    C:\ProgramData\nuget\Config\Microsoft.VisualStudio.Offline.config

Feeds used:
    https://api.nuget.org/v3/index.json
    C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
```

Then I tried:

`PM> dotnet ef database update`

and got the error:

`[1m[31mNo executable found matching command "dotnet-ef"[39m[22m`

**My environment is:**

```
PM> dotnet --info
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
PM> 
```

I tried several EF command line solutions I found throughout the internet but none solved (including completely removing .nuget/package from my machine).

Is there any other way to get around this issue?

Thanks!

**Comment by hikalkan** [comment] 2016-07-08 07:43
not "dotnet-ef", but "dotnet ef" (no dash):

````
dotnet ef database update
````

**Comment by jotamorais** [comment] 2016-07-13 19:48
There is no dash in the command I'm running. This is exactly what I had tried. See:

![image](https://cloud.githubusercontent.com/assets/5201388/16817526/8b77ea18-4919-11e6-9628-606fe9cdfee2.png)

**Comment by hikalkan** [comment] 2016-07-13 20:27
Hi,

I think somehow it's not installed on your machine (if you built project). Have you installed ASP.NET Core 1.0?

But this is not related to ABP since it's standard command of EF. See it's documentation: https://docs.efproject.net/en/latest/miscellaneous/cli/dotnet.html#dotnet-ef-database-update

**Comment by Korigoth** [comment] 2016-07-17 02:56
I have the same problem and i didn't find anything that permit me to run the "dotnet ef database update" command. 

I tried with PowerShell, Cmd, Package manager and still i have the same error on those 3 command line tools.

I didn't find any solution on https://docs.efproject.net/en/latest/miscellaneous/cli/dotnet.html#dotnet-ef-database-update that helped me to understand the error.

If you can help us to find what is missing it could help for the testing of the Core Template.

**Comment by hikalkan** [comment] 2016-07-17 09:22
Can you run same command for a regular ASP.NET Core project with EF Core integrated but without using ABP?

**Comment by Korigoth** [comment] 2016-07-17 13:51
Yea the same problem happen on an other project i have with ASP.Net Core.
 So yea it's not ABP Fault, but i didn't find any answer yet!

I don't know if i'm missing something or do i need to install something else than ASP.Net Core ?

Here is my Visual Studio Info if you can compare with yours?

Microsoft Visual Studio Community 2015
Version 14.0.25422.01 Update 3
Microsoft .NET Framework
Version 4.6.01055

Installed Version: Community

Microsoft Visual Studio Tools for Applications 2015   00322-20000-00000-AA747
Microsoft Visual Studio Tools for Applications 2015

Visual Basic 2015   00322-20000-00000-AA747
Microsoft Visual Basic 2015

Visual C# 2015   00322-20000-00000-AA747
Microsoft Visual C# 2015

Visual C++ 2015   00322-20000-00000-AA747
Microsoft Visual C++ 2015

Application Insights Tools for Visual Studio Package   7.0.20622.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015.1   14.1.20624.0
ASP.NET and Web Tools 2015.1

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Azure App Service Tools v2.9   14.0.20316.0
Azure App Service Tools v2.9

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.0.6000.0
Microsoft Azure Data Lake Tools for Visual Studio

Common Azure Tools   1.8
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GitHub.VisualStudio   1.0
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

Microsoft .NET Core Tools (Preview 2)   14.1.20624.0
Microsoft .NET Core Tools (Preview 2)

Microsoft Azure HDInsight HQL Service   2.0.6000.0
Language service for Hive query

Microsoft Azure HDInsight Tools for Visual Studio   2.0.6000.0
An integrated development environment for HDInsight application development.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.9.40323.3

NuGet Package Manager   3.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Analysis Services   13.0.1601.5
Microsoft SQL Server Analysis Services Designer 
Version 13.0.1601.5

SQL Server Data Tools   14.0.60525.0
Microsoft SQL Server Data Tools

SQL Server Integration Services   
Microsoft SQL Server Integration Services Designer
Version 13.0.1601.5

SQL Server Reporting Services   13.0.1601.5
Microsoft SQL Server Reporting Services Designers 
Version 13.0.1601.5

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript   1.8.35.0
TypeScript tools for Visual Studio

Visual Studio Tools for Unity   2.3.0.0
Visual Studio Tools for Unity

Web Compiler   1.11.315
Compiler for LESS, Sass and CoffeeScript files

**Comment by hikalkan** [comment] 2016-07-18 11:42
And this is mine:

Microsoft Visual Studio Enterprise 2015
Version 14.0.25422.01 Update 3
Microsoft .NET Framework
Version 4.6.01038

Installed Version: Enterprise

Architecture and Modeling Tools   00322-90150-00888-AA084
Microsoft Architecture and Modeling Tools
    
UML® and Unified Modeling Language™ are trademarks or registered trademarks of the Object Management Group, Inc. in the United States and other countries.

Visual Basic 2015   00322-90150-00888-AA084
Microsoft Visual Basic 2015

Visual C# 2015   00322-90150-00888-AA084
Microsoft Visual C# 2015

Visual C++ 2015   00322-90150-00888-AA084
Microsoft Visual C++ 2015

Windows Phone SDK 8.0 - ENU   00322-90150-00888-AA084
Windows Phone SDK 8.0 - ENU

Add New File   3.4
The fastest and easiest way to add new files to any project - including files that start with a dot

ASP.NET and Web Tools 2015.1   14.1.20624.0
ASP.NET and Web Tools 2015.1

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Azure App Service Tools v2.8.1   14.0.11123.0
Azure App Service Tools v2.8.1

Bundler & Minifier   2.1.258
Adds support for bundling and minifying JavaScript, CSS and HTML files in any project.

BusinessObjectEditor   1.0
Information about my package

Common Azure Tools   1.8
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

DevExpress.DeploymentTool   1.0
A useful tool for deploying DevExpress assemblies.

DevExpress.ExpressApp.Design.DynamicPackage   1.0
DevExpress VSIX Package

DevExpress.ExpressApp.DesignPackage   1.0
DevExpress VSIX Package

File Nesting   2.5.62
Automatically nest files based on file name and enables developers to nest and unnest any file manually

GhostDoc   4.9.15086.0
GhostDoc automatically generates XML documentation comments.

GitHub.VisualStudio   1.0
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

Image Optimizer   3.6.89
Uses industry standard tools to optimize any JPEG, PNG and Gifs - including animated Gifs. Can do both lossy and lossless optimization.

Image Sprites   1.2.36
Boost your website's performance by creating image sprites to reduce the amount of HTTP requests needed.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JetBrains ReSharper Ultimate 2016.2 EAP 6   Build 106.0.20160629.133723-eap6
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2016 JetBrains, Inc.

Markdown Editor   1.5.110
A full featured Markdown editor with live preview and syntax highligting. Supports GitHub flavored Markdown.

Microsoft .NET Core Tools (Preview 2)   14.1.20624.0
Microsoft .NET Core Tools (Preview 2)

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

NuGet Package Manager   3.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

NuProjPackage   1.0
NuGet Package Project System

Open Command Line   2.1.175
Opens a command line at the root of the project. Support for all consoles such as CMD, PowerShell, Bash etc. Provides syntax highlighting, Intellisense and execution of .cmd and .bat files.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   14.0.60519.0
Microsoft SQL Server Data Tools

Suggested Extensions   1.1.71
Get suggestions on what extensions you need to handle various file types and projects when you need them.

TargetFrameworkMigrator   1.0
Bulk Change .Net Projects Target Frameworks

TypeScript   1.8.35.0
TypeScript tools for Visual Studio

Visual Studio Spell Check Everywhere   VSSpellCheckEverywhere
An extension that enables spell checking within any Visual Studio file editor or tool window that uses WPF text boxes.
https://GitHub.com/EWSoftware/VSSpellChecker

Visual Studio Spell Checker   VSSpellChecker
An editor extension that checks the spelling of comments, strings, and plain text as you type or interactively with tool windows.
https://GitHub.com/EWSoftware/VSSpellChecker

Visual Studio Tools for Apache Cordova   Update 10
Visual Studio Tools for Apache Cordova

Visual Studio Tools for Universal Windows Apps   14.0.25420.01
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

Web Compiler   1.11.315
Compiler for LESS, Sass and CoffeeScript files

Web Essentials 2015.3   3.0.230
Adds many useful features to Visual Studio for web developers. Requires Visual Studio 2015

Xamarin   4.1.0.530 (2e39740)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android   6.1.0.71 (4e27558)
Visual Studio extension to enable development for Xamarin.Android.

Xamarin.iOS   9.8.0.323 (39ebb77)
Visual Studio extension to enable development for Xamarin.iOS.

**Comment by Korigoth** [comment] 2016-07-19 00:38
I will need to check it in depth during the week

Is it possible that you share your PATH variable ? Or tell me if there is something about dotnet in your environment variables.

I've seen some people talking about VS Update that fucked up those environment variable!

For me, there is no PATH variable anymore in my system... so i guess it may be the case...

**Comment by hikalkan** [comment] 2016-07-19 05:56
Hi,

I have a line in path variable as below:

``C:\Program Files\dotnet\``

My OS is Windows 10 x64.

**Comment by arthurspa** [comment] 2016-07-19 14:24
I have the same problem using VS Community. Also tried using command line but got same error.
Recently I updated from VS Update 2 to Update 3. 
@Korigoth , if reinstalling VS 2015 completely solves the problem, please tell us.

I'm running Windows 8.1 x64.

**Comment by Korigoth** [comment] 2016-07-19 20:49
@arthurspa For sure, if i find the solution, i will post it !

@hikalkan Thx, definitly i'm missing this in my path variable!

I cannot test until tomorrow night i'm pretty busy these days but yesterday, i did a repair of VS2015 Update3. So i will check tomorrow if it fixed something, if not i will try to check if the PATH variable with the dotnet path fix something and finally if it's still broken i will reinstall completly VS.

**Comment by arthurspa** [comment] 2016-07-20 17:03
I could get it working. Try to repeate the **"Microsoft.EntityFrameworkCore.Tools"** package into **"tools"** key located in **.EntityFrameworkCore\project.json** file.

```
"dependencies": {
    "Abp.EntityFrameworkCore": "0.10.0.1",
    "AbpCompanyName.AbpProjectName.Core": "1.0.0.0-*",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final"
  },

  "tools": {
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final"
  },
```

Then, restore packages. Also, make sure to set the correct connection string.

Now I'm using VS Enterprise Update 3. Also, I changed the sdk version to the latest in global.json:

```
{
  "projects": [ "src", "test" ],
  "sdk": {
    "version": "1.0.0-preview2-003121"
  }
}
```

**Comment by Korigoth** [comment] 2016-07-20 21:26
i still get the error when 
- Adding tool in Core project.json,
- Adding the new version to global.json,
- running dotnet restore in package manager
- running dotnet ef database update

my connection string is in Web appsettings.json and is correct

here is my dotnet --info
PM> dotnet --info
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64

**Comment by Korigoth** [comment] 2016-07-20 21:28
the command 
dotnet ef        is not recognized, do you have something in ur path variable?
i've added the PATH variable and the value to dotnet in program files.

**Comment by arthurspa** [comment] 2016-07-20 21:43
My `dotnet --info` shows exactly same output as yours.

In my system PATH I have `C:\Program Files\dotnet\`.

You may try to clear packages in `C:\Users\%YOUR_USER_NAME%\.nuget\packages\`. Then, do a `dotnet restore`.

**Comment by Korigoth** [comment] 2016-07-20 22:11
same error happen, i did 
- i have my PATH variable to  C:\Program Files\dotnet\
- Deleted everything under C:\Users\MyName\.nuget\packages\
- In package manager of web dotnet restore
- changed the package manager to EntityFramework    dotnet ef database update

and getting the error:

dotnet : No executable found matching command "dotnet-ef"
At line:1 char:1
+ dotnet ef database update
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (No executable f...and "dotnet-ef":String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

**Comment by Korigoth** [comment] 2016-07-21 02:44
I got it working in a new project of ASP.Net Core with Individual Account.
I needed to CD to the project.json then use the command  dotnet ef database update and it worked!

So the problem is now related to ABP because it doesn't work with ABP but it work in my other solution now!

**Comment by hikalkan** [comment] 2016-07-21 07:02
OK,
it seems related to project.json in the solution. I will work on it to make it working.

**Comment by hikalkan** [comment] 2016-07-21 13:14
I had the same problem. https://github.com/aspnet/EntityFramework/issues/5458#issuecomment-221912806 fixed my problem.
Now, I tested our solution in 3 different computer and all they works.

**Comment by ArturKarbone** [comment] 2016-07-21 13:56
In my project.json tools section looks like this and it is enough to run **dotnet ef**
 "tools": {
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final"
  },

**Comment by hikalkan** [comment] 2016-07-21 15:54
Thank you. We are waiting everyone to test, then I'll close this issue.

**Comment by arthurspa** [comment] 2016-07-21 19:51
As I mentioned above, I had to change the version of the sdk in `global.json` from `1.0.0-preview1-002702` to current version, which is as of today, `1.0.0-preview2-003121`, otherwise I receive the following error:

![error](https://cloud.githubusercontent.com/assets/3959458/17036514/98493084-4f5a-11e6-97e8-4c390b523da1.png)

**Comment by Korigoth** [comment] 2016-07-21 23:38
Oh Yeah!  
Replacing the version in global.json and adding tools to the project.json of entityframework work !! :D

thx a lot guys! :)

**Comment by hikalkan** [comment] 2016-07-22 06:54
Thank you all. I'm closing this one. You can re-open if it's not fixed.

**Closed by hikalkan** 2016-07-22 06:54 UTC
Labels: bug

**Comment by ChiakiYu** [comment] 2017-04-10 05:23
so ,how to solve the problem?

**Comment by hikalkan** [comment] 2017-04-10 13:42
There is no project.json & global.json anymore since we migrated to VS 2017 project format.

**Comment by ChiakiYu** [comment] 2017-04-11 00:36
I know.
`dotnet ef database update` should run in cmd.exe
